# Generated by Django 2.2.16 on 2022-03-30 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Введите название произведения', verbose_name='Название произведения')),
                ('title_urls', models.URLField(blank=True, null=True, unique=True)),
                ('release', models.DateField(help_text='Введите дату публикации', verbose_name='Дата публикации')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='composition.Author', verbose_name='Автор')),
                ('categories', models.ForeignKey(help_text='Введите категорию произведения', on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='composition.Categories', verbose_name='Категория')),
                ('genre', models.ForeignKey(blank=True, help_text='Введите жанры произведения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='composition.Genres', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Произведение',
                'verbose_name_plural': 'Произведения',
                'ordering': ['-release'],
            },
        ),
    ]
